/*
 * Thingdust app API
 *
 * API to access and configure the Thingdust app
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// Space - The schema `Space` maps each pair of Eliona project id and thingdust space to an Eliona asset. For different Eliona projects different assets are used (see `proj_ids` in `Configuration`). The mapping is created automatically by the app and should used read only.
type Space struct {

	// References the configured endpoint (see `Configuration`)
	ConfigId int32 `json:"configId,omitempty"`

	// The project id for which the Eliona asset is created (see `proj_ids` in `Configuration`)
	ProjId string `json:"projId,omitempty"`

	// References the asset id in Eliona which is automatically created by the app
	AssetId int32 `json:"assetId,omitempty"`

	// References to the thingdust space
	SpaceName string `json:"spaceName,omitempty"`
}

// AssertSpaceRequired checks if the required fields are not zero-ed
func AssertSpaceRequired(obj Space) error {
	return nil
}

// AssertRecurseSpaceRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Space (e.g. [][]Space), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseSpaceRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aSpace, ok := obj.(Space)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertSpaceRequired(aSpace)
	})
}
